### PR TITLE
Add typescript types and use NPM files filter

### PR DESCRIPTION
**Pull request by NickBolles**

### CODE REVIEW

**Comment by NickBolles** [comment]
Tested in my app with `yarn add https://github.com/NickBolles/mongo-connection-string.git`

**Comment by dwmkerr** [comment]
This is super useful, thanks @NickBolles!

**Comment by dwmkerr** [comment]
Released in `0.1.5`

**Comment by NickBolles** [comment]
Whoah! That was fast! Thanks @dwmkerr!

**Comment by dwmkerr** [comment]
No worries, thanks for the contribution!

**Pull request merged**
